IP_SOCKET: '127.0.0.1' # endereço IP que o servidor vai rodar
PORTA_SOCKET: 8888 # porta que o servidor vai rodar
TAMANHO_MAXIMO_PACOTE: 3134 # 3Kb tamanho máximo do dado enviado a cada vez
BASH: xfce4-terminal
PYTHON3: /usr/bin/python3
DIR_LOG: 'logs/'
DIR_SNAP: 'snaps/'
SLEEP_TIME : 10