IP_SOCKET: '127.0.0.1' # endereço IP que o servidor vai rodar
BASH: x-terminal-emulator
BASH_PARAMS: --geometry 60x10 --title 'Servidor {}'
PYTHON: /usr/bin/python3
SERVIDORES: ./servidores.txt
DB_PARAMS: ./db_params.yaml
PREFIXO_PORTA: '199'
DB_INTERFACE: concoord object -o banco_de_dados.BancoDeDados
DB_PATH: export PYTHONPATH=$PYTHONPATH
